env:
  node: true
  es2021: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  "import/no-named-as-default": 0
  no-console: 0
  no-await-in-loop: off
  import/extensions: 0
  "import/no-named-as-default-member": 0
